**Sakshi Kharat**

**Oasis Infobyte (Data Science) - Task-4**


**Email Spam Detection using Machine Learning**

**About the Task- 4:
Spam mails or junk mails are sent to the massive number of users at the same time, frequently containing the spam messages, scams or most dangerously, phishing content.
This project will use Machine Learning to recognize and Classify Emails into Spam and non-spam**  

In [1]:
import pandas as pd

In [2]:
import matplotlib as plt

In [3]:
import numpy as np

**Data Collection**

In [4]:
from google.colab import files


uploaded = files.upload()

Saving spam.csv to spam.csv


In [7]:
df = pd.read_csv('spam.csv', encoding='latin-1')


**Viewing the Dataset**


In [8]:
df

Category                                            Message Unnamed: 2  \
0         ham  Go until jurong point, crazy.. Available only ...        NaN   
1         ham                      Ok lar... Joking wif u oni...        NaN   
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3         ham  U dun say so early hor... U c already then say...        NaN   
4         ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...       ...                                                ...        ...   
5567     spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568      ham              Will Ì_ b going to esplanade fr home?        NaN   
5569      ham  Pity, * was in mood for that. So...any other s...        NaN   
5570      ham  The guy did some bitching but I acted like i'd...        NaN   
5571      ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

**Displaying the Dataset**

In [9]:
df.info

<bound method DataFrame.info of      Category                                            Message Unnamed: 2  \
0         ham  Go until jurong point, crazy.. Available only ...        NaN   
1         ham                      Ok lar... Joking wif u oni...        NaN   
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3         ham  U dun say so early hor... U c already then say...        NaN   
4         ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...       ...                                                ...        ...   
5567     spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568      ham              Will Ì_ b going to esplanade fr home?        NaN   
5569      ham  Pity, * was in mood for that. So...any other s...        NaN   
5570      ham  The guy did some bitching but I acted like i'd...        NaN   
5571      ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unn

**Dropping the null values**

In [10]:
df_cleaned = df.drop(["Unnamed: 2","Unnamed: 3","Unnamed: 4"], axis=1)

In [11]:
df_cleaned

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham              Will Ì_ b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

**There are 5572 rows and 2 columns**

**Data Preprocessing**

In [14]:
df_cleaned.columns

Index(['Category', 'Message'], dtype='object')

**There are total 2 columns in the Dataset**

In [15]:
df_cleaned.shape

(5572, 2)

In [16]:
df_cleaned.head(2)

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...

**Displaying the first 2 entries of the Dataset**

In [17]:
df_cleaned.tail(2)

Category                                            Message
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

**Displaying the last 2 entries of the Dataset**


In [18]:
df_cleaned.iloc[1]

Category                              ham
Message     Ok lar... Joking wif u oni...
Name: 1, dtype: object

**Preprocessing the Data**

Checking the Null Values

In [19]:
df_cleaned.isnull()

Category  Message
0        False    False
1        False    False
2        False    False
3        False    False
4        False    False
...        ...      ...
5567     False    False
5568     False    False
5569     False    False
5570     False    False
5571     False    False

[5572 rows x 2 columns]

In [20]:
df_cleaned.isnull().sum()

Category    0
Message     0
dtype: int64

In [21]:
df_cleaned.isna().sum()

Category    0
Message     0
dtype: int64

**Label Encoding**

In [28]:
df_cleaned.loc[df_cleaned['Category'] == 'spam', 'Category',] = 0
df_cleaned.loc[df_cleaned['Category'] == 'ham', 'Category',] = 1


In [29]:
df_cleaned.head(4)

Category                                            Message  Spam
0        1  Go until jurong point, crazy.. Available only ...     0
1        1                      Ok lar... Joking wif u oni...     0
2        0  Free entry in 2 a wkly comp to win FA Cup fina...     1
3        1  U dun say so early hor... U c already then say...     0

**Splitting the data into to training data and test data**

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

**Using CountVectorizer class from scikit-learn to convert the text data into a bag-of-words representation.**

In [32]:
from sklearn.naive_bayes import MultinomialNB

In [33]:
from sklearn.metrics import accuracy_score

In [34]:
from sklearn import preprocessing


In [35]:
lab = preprocessing.LabelEncoder()

In [49]:
df_cleaned['Category'] = lab.fit_transform(df_cleaned['Category'])

<ipython-input-49-30359793f41d>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned['Category'] = lab.fit_transform(df_cleaned['Category'])


**Droping the Duplicate Values**

In [50]:
df_cleaned.duplicated().sum()


0

**403 are the Duplicate Values**


In [51]:
df_cleaned  = df_cleaned.drop_duplicates()

In [52]:
df_cleaned.duplicated().sum()

0

**Splitting the data**


In [53]:
x = df_cleaned['Message']

In [54]:
y = df_cleaned['Category']

In [55]:
x_train, x_test, y_train, y_test =train_test_split(x,y, test_size=0.25, random_state=0)

**Feature Extraxtion - converting text into numerical values**

In [56]:
from sklearn.pipeline import Pipeline

In [57]:
clt=Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

**Training the model**

In [58]:
clt.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [59]:
Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [60]:
emails=[
    'Sounds great! Are you home now?',
    'Will u meet ur dream partner soon? Is ur career off 2 a flyng start? 2 find out free, txt HORO followed by ur star sign, e. g. HORO ARIES'
]

In [61]:
clt.predict(emails)

array([1, 0])

In [62]:
clt.score(x_test,y_test)

0.9845320959010054

In [63]:
clt.score(x_train, y_train)

0.9938080495356038

In [64]:
emails=[
    'I m gonna be home soon and i dont want to talk about this stuff anymore tonight, k? Ive cried enough today.',
    'WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.'
]

In [65]:
clt.predict(emails)

array([1, 0])

In [66]:
emails=[
    'Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030',
    'SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info'
]

In [67]:
clt.predict(emails)

array([0, 0])

**End of the Code**